---
- hosts: localhost
  gather_facts: false
  vars:
    current_date: "{{ lookup('pipe','date +%Y-%m-%d') }}"
  tasks:
    - name: Commit and push in /infra/
      shell: |
        git add .
        if ! git diff-index --quiet HEAD --; then
          git commit -m "{{ current_date }} - автоматический коммит"
          git push origin master
        else
          echo "No changes to commit in /infra/"
        fi
      args:
        chdir: /infra

    - name: Commit and push in /infra/roles/
      shell: |
        git add .
        if ! git diff-index --quiet HEAD --; then
          git commit -m "{{ current_date }} - автоматический коммит"
          git push origin master
        else
          echo "No changes to commit in /infra/roles/"
        fi
      args:
        chdir: /infra/roles
