---
- hosts: localhost
  gather_facts: false
  vars:
    current_date: "{{ lookup('pipe','date +%Y-%m-%d') }}"
    git_dirs:
      - /infra
      - /infra/roles

  tasks:
    - name: Check for changes, commit and push
      shell: |
        git add .
        if ! git diff-index --quiet HEAD --; then
          git commit -m "{{ current_date }} - автоматический коммит"
          git push origin master
          echo "pushed"
        else
          echo "no changes"
        fi
      args:
        chdir: "{{ item }}"
      loop: "{{ git_dirs }}"
      register: git_result
      changed_when: false

    - name: Show concise results
      debug:
        msg: "{{ item.item }}: {{ item.stdout }}"
      loop: "{{ git_result.results }}"
